// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btdlteveqdhvrdcawckw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0ZGx0ZXZlcWRodnJkY2F3Y2t3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0Mzk2NzAsImV4cCI6MjA3MjAxNTY3MH0.KdQdmgJ2T9OmQY_oYMPVaJ4-9DaaN2YJwk1y6plphNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});